name: videogame_store
services:
  postgres:
    image: postgres:latest
    container_name: videogame_store_db
    restart: 'no'
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=devco
      - POSTGRES_PASSWORD=devco
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./scripts/initialize_db.sh:/docker-entrypoint-initdb.d/initialize_db.sh
    command: sh -c "chmod +x /docker-entrypoint-initdb.d/initialize_db.sh && docker-entrypoint.sh postgres"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: 'no'
    ports:
      - "5555:80"
    volumes:
      - ./config/servers.json:/pgadmin4/servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_DEFAULT_FEATURES=/pgadmin4/servers.json
    depends_on:
      - postgres

  app:
    container_name: videogame_store_app
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src

networks:
  default:
    name: postgres-service-default